### ISSUE TITLE
I need your help 

### ISSUE THREAD

**Issue by Johnelmer227** [HemanthJabalpuri/twrp_realme_RMX2195#1]
Hello developers my phone is bricked but i have your TWRP when i'm trying to flash to gsi rom and got bootloop when i'm trying to back to stock rom from realme website and i got error "asset failed: update_dynamic_partitions (package_extract_file("dynamic_partition_op_list")) with error 7 but my ozip file is not corrupted. and there is no custom rom from this device. What should i do? and how can i use the 3 patches now?

**Comment by Johnelmer227** [comment]
> @Johnelmer227 What's the status of your mobile now?

Hello  i have the one issue after i flash stock rom. My SIM card has "no network coverage" How can i fic this??

**Comment by HemanthJabalpuri** [comment]
Sorry, don't know about those.
Actually I don't have C15 QCom, but a person asked me to make TWRP, since it will make flashingbstock ROM easier when we are GSIs or soft brick.

Thanks

**Comment by Johnelmer227** [comment]
> Sorry, don't know about those. Actually I don't have C15 QCom, but a person asked me to make TWRP, since it will make flashing stock ROM easier when we are using GSIs or soft brick mobile.
> 
> Thanks

Hello That's ok Thank you...

**Comment by Johnelmer227** [comment]
I closed the issues
